virtual void onDisconnected(int reason){};
virtual void onError(dict error){};
virtual void onSubMarketData(dict data, dict error, bool last){};
virtual void onUnSubMarketData(dict data, dict error, bool last){};
virtual void onDepthMarketData(dict data){};
virtual void onSubOrderBook(dict data, dict error, bool last){};
virtual void onUnSubOrderBook(dict data, dict error, bool last){};
virtual void onOrderBook(dict data){};
virtual void onSubTickByTick(dict data, dict error, bool last){};
virtual void onUnSubTickByTick(dict data, dict error, bool last){};
virtual void onTickByTick(dict data){};
virtual void onSubscribeAllMarketData(dict error){};
virtual void onUnSubscribeAllMarketData(dict error){};
virtual void onSubscribeAllOrderBook(dict error){};
virtual void onUnSubscribeAllOrderBook(dict error){};
virtual void onSubscribeAllTickByTick(dict error){};
virtual void onUnSubscribeAllTickByTick(dict error){};
virtual void onQueryAllTickers(dict data, dict error, bool last){};
virtual void onQueryTickersPriceInfo(dict data, dict error, bool last){};
