void processTask();
void processDisconnected(Task *task);
void processError(Task *task);
void processOrderEvent(Task *task);
void processTradeEvent(Task *task);
void processCancelOrderError(Task *task);
void processQueryOrder(Task *task);
void processQueryTrade(Task *task);
void processQueryPosition(Task *task);
void processQueryAsset(Task *task);
void processQueryStructuredFund(Task *task);
void processQueryFundTransfer(Task *task);
void processFundTransfer(Task *task);
void processQueryETF(Task *task);
void processQueryETFBasket(Task *task);
void processQueryIPOInfoList(Task *task);
void processQueryIPOQuotaInfo(Task *task);
