void release();
string getTradingDay();
void registerSpi(MIGHT WRONG spi);
MIGHT WRONG getApiLastError();
string getApiVersion();
uint8_t getClientIDByXTPID(uint64_t order_xtp_id);
string getAccountByXTPID(uint64_t order_xtp_id);
void subscribePublicTopic(int resume_type);
void setSoftwareVersion(string version);
void setSoftwareKey(string key);
void setHeartBeatInterval(uint32_t interval);
uint64_t login(string ip, int port, string user, string password, int sock_type);
int logout(uint64_t session_id);
uint64_t insertOrder(dict data, uint64_t session_id);
uint64_t cancelOrder(uint64_t order_xtp_id, uint64_t session_id);
int queryOrderByXTPID(uint64_t order_xtp_id, uint64_t session_id, int request_id);
int queryOrders(dict data, uint64_t session_id, int request_id);
int queryTradesByXTPID(uint64_t order_xtp_id, uint64_t session_id, int request_id);
int queryTrades(dict data, uint64_t session_id, int request_id);
int queryPosition(string ticker, uint64_t session_id, int request_id);
int queryAsset(uint64_t session_id, int request_id);
int queryStructuredFund(dict data, uint64_t session_id, int request_id);
uint64_t fundTransfer(dict data, uint64_t session_id);
int queryFundTransfer(dict data, uint64_t session_id, int request_id);
int queryETF(dict data, uint64_t session_id, int request_id);
int queryETFTickerBasket(dict data, uint64_t session_id, int request_id);
int queryIPOInfoList(uint64_t session_id, int request_id);
int queryIPOQuotaInfo(uint64_t session_id, int request_id);
